Working updates from my environment

diff --git a/compose/bin/setup b/compose/bin/setup
--- a/compose/bin/setup
+++ b/compose/bin/setup
@@ -1,55 +1,55 @@
-#!/usr/bin/env bash
+#!/bin/bash
+
 set -o errexit
 
-MEM_BYTES=$(docker info -f '{{.MemTotal}}')
-MEM_MB=$(( MEM_BYTES / 1000000 ))
-# When Docker Desktop is set to 6GB in the GUI, it is reported as 6227 MB
-(( MEM_MB < 6227 )) && echo "There must be at least 6GB of RAM allocated to Docker in order to continue." && exit
+[[ -z "${BIN_DIR}" ]] && BIN_DIR="$(dirname "$0")"
+[[ -z "${PROJECT_ROOT}" ]] && PROJECT_ROOT="$(dirname "${BIN_DIR}")"
 
 DOMAIN=${1:-magento.test}
 
-bin/stop
+"${BIN_DIR}/stop"
 
-bin/start --no-dev
-[ $? != 0 ] && echo "Failed to start Docker services" && exit
+if ! "${BIN_DIR}/start" --no-dev; then
+  echo "Failed to start Docker services"
+  exit
+fi
 
-bin/clinotty chmod u+x bin/magento
-rm -rf src && mkdir src
+"${BIN_DIR}/clinotty" chmod u+x bin/magento
+rm -rf "${PROJECT_ROOT}/src" && mkdir "${PROJECT_ROOT}/src"
+
+echo "Installing Data Solutions Dev Requirements"
+# Install services-connector jwt dependency
+"${BIN_DIR}/composer" require firebase/php-jwt gmostafa/php-graphql-client
 
 echo "Adding Magento modules to Composer allow-plugins directive..."
-bin/clinotty composer config --no-plugins allow-plugins.magento/magento-composer-installer true
-bin/clinotty composer config --no-plugins allow-plugins.magento/inventory-composer-installer true
-bin/clinotty composer config --no-plugins allow-plugins.laminas/laminas-dependency-plugin true
+"${BIN_DIR}/clinotty" composer config --no-plugins allow-plugins.magento/magento-composer-installer true
+"${BIN_DIR}/clinotty" composer config --no-plugins allow-plugins.magento/inventory-composer-installer true
+"${BIN_DIR}/clinotty" composer config --no-plugins allow-plugins.laminas/laminas-dependency-plugin true
 
 echo "Running, Magento setup:install..."
-bin/setup-install "${DOMAIN}"
+"${BIN_DIR}/setup-install" "${DOMAIN}"
 
 echo "Copying files from container to host after install..."
-bin/copyfromcontainer --all
+"${BIN_DIR}/copyfromcontainer" --all
 
 echo "Forcing deploy of static content to speed up initial requests..."
-bin/clinotty bin/magento setup:static-content:deploy -f
-
-echo "Re-indexing with Elasticsearch..."
-bin/clinotty bin/magento indexer:reindex
+"${BIN_DIR}/clinotty" bin/magento setup:static-content:deploy -f
 
 echo "Setting basic URL and generating SSL certificate..."
-bin/setup-domain "${DOMAIN}"
+"${BIN_DIR}/setup-domain" "${DOMAIN}"
 
 echo "Fixing owner and permissions..."
-bin/fixowns
-bin/fixperms
+"${BIN_DIR}/fixowns"
+"${BIN_DIR}/fixperms"
 
 echo "Clearing the cache to apply updates..."
-bin/clinotty bin/magento cache:flush
+"${BIN_DIR}/clinotty" bin/magento cache:flush
 
 echo "Installing cron, run 'bin/cron start' to enable..."
-bin/clinotty bin/magento cron:install
+"${BIN_DIR}/clinotty" bin/magento cron:install
 
 echo "Turning on developer mode..."
-bin/clinotty bin/magento deploy:mode:set developer
-
-cp -r .vscode src/
+"${BIN_DIR}/clinotty" bin/magento deploy:mode:set developer
 
 echo "Docker development environment setup complete."
 echo "You may now access your Magento instance at https://${DOMAIN}/"
